disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string

line_length:
  warning: 140
  error: 200

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length: 3
  max_length: 60
  excluded:
    - id
    - URL
    - GlobalAPIKey
