# XcodeGen – run: xcodegen generate
name: AppFoundation
options:
  bundleIdPrefix: com.tomthecat
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
configs:
  Debug: debug
  Release: release
  Local: debug
postGenCommand: pod install
packages:
  Swinject:
    url: https://github.com/Swinject/Swinject
    from: "2.8.0"
  RealmSwift:
    url: https://github.com/realm/realm-swift
    from: "10.40.0"
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: "5.9.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: "7.0.0"
targets:
  AppFoundation:
    type: application
    platform: iOS
    sources:
      - path: Sources/AppFoundation
        name: AppFoundation
      - path: Sources/AppFoundationUI
        name: AppFoundationUI
      - path: Sources/AppFoundationAuth
        name: AppFoundationAuth
      - path: Sources/AppFoundationResources
        name: AppFoundationResources
      - path: Sources/AppFoundationExample
        name: AppFoundationExample
    settings:
      base: Config/Shared.xcconfig
      configFiles:
        Debug: Config/Dev.xcconfig
        Release: Config/Production.xcconfig
        Local: Config/Local.xcconfig
      PRODUCT_BUNDLE_IDENTIFIER: com.tomthecat.AppFoundation
      INFOPLIST_FILE: AppFoundation/Info.plist
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Swinject
        product: Swinject
      - package: RealmSwift
        product: RealmSwift
      - package: Alamofire
        product: Alamofire
      - package: Kingfisher
        product: Kingfisher
    postBuildScripts:
      - name: SwiftLint
        script: |
          if [ -f "${PODS_ROOT}/SwiftLint/swiftlint" ]; then
            "${PODS_ROOT}/SwiftLint/swiftlint" || true
          else
            echo "warning: SwiftLint not installed"
          fi
    info:
      path: AppFoundation/Info.plist
      generate: false
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientation.portrait, UIInterfaceOrientation.landscapeLeft, UIInterfaceOrientation.landscapeRight]
  AppFoundationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/AppFoundationTests
        name: AppFoundationTests
    dependencies:
      - target: AppFoundation
      - package: Swinject
        product: Swinject
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tomthecat.AppFoundationTests
      GENERATE_INFOPLIST_FILE: YES
  AppFoundationUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
        name: AppFoundationUITests
    dependencies:
      - target: AppFoundation
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tomthecat.AppFoundationUITests
      GENERATE_INFOPLIST_FILE: YES
schemes:
  AppFoundation:
    build:
      targets:
        AppFoundation: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AppFoundationTests
        - AppFoundationUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  "AppFoundation (Local)":
    build:
      targets:
        AppFoundation: all
    run:
      config: Local
    test:
      config: Local
      targets:
        - AppFoundationTests
        - AppFoundationUITests
    profile:
      config: Local
    analyze:
      config: Local
    archive:
      config: Local