# XcodeGen – run: xcodegen generate
name: AppFoundation
options:
  bundleIdPrefix: com.tomthecat
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

configs:
  Debug: debug
  Release: release

packages:
  Swinject:
    url: https://github.com/Swinject/Swinject
    from: "2.8.0"
  RealmSwift:
    url: https://github.com/realm/realm-swift
    from: "10.40.0"
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: "5.9.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: "7.0.0"

targets:
  AppFoundationResources:
    type: framework
    platform: iOS
    sources:
      - path: Sources/AppFoundationResources
    settings:
      GENERATE_INFOPLIST_FILE: YES

  AppFoundation:
    type: framework
    platform: iOS
    sources:
      - path: Sources/AppFoundation
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppFoundationResources
      - package: Swinject
      - package: RealmSwift
      - package: Alamofire

  AppFoundationUI:
    type: framework
    platform: iOS
    sources:
      - path: Sources/AppFoundationUI
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppFoundation
      - target: AppFoundationResources
      - package: Kingfisher

  AppFoundationAuth:
    type: framework
    platform: iOS
    sources:
      - path: Sources/AppFoundationAuth
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppFoundation
      - target: AppFoundationUI
      - target: AppFoundationResources

  AppFoundationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/AppFoundationTests
    dependencies:
      - target: AppFoundation
      - target: AppFoundationUI
      - target: AppFoundationAuth
      - package: Swinject
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tomthecat.AppFoundationTests
      GENERATE_INFOPLIST_FILE: YES

schemes:
  AppFoundation:
    build:
      targets:
        AppFoundation: all
        AppFoundationUI: all
        AppFoundationAuth: all
        AppFoundationResources: all
    test:
      config: Debug
      targets:
        - AppFoundationTests