//
//  LoginViewModel.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation
import Combine

// Note: If using BaseViewModel, remove @MainActor (BaseViewModel is already @MainActor)
// If standalone, keep @MainActor annotation

final class LoginViewModel: ObservableObject {
    // MARK: - Published Properties
    @Published var email: String = ""
    @Published var password: String = ""
    @Published var isLoading: Bool = false
    @Published var errorMessage: String?
    @Published var isAuthenticated: Bool = false
    
    // MARK: - Dependencies
    private let loginUseCase: LoginUseCaseProtocol
    private var onLoginSuccess: (() -> Void)?
    private var cancellables = Set<AnyCancellable>()
    
    // MARK: - Initialization
    init(loginUseCase: LoginUseCaseProtocol, onLoginSuccess: (() -> Void)? = nil) {
        self.loginUseCase = loginUseCase
        self.onLoginSuccess = onLoginSuccess
    }
    
    // MARK: - Actions
    @MainActor
    func login() async {
        guard validate() else { return }
        
        isLoading = true
        errorMessage = nil
        
        do {
            let user = try await loginUseCase.execute(email: email, password: password)
            isAuthenticated = true
            onLoginSuccess?()
            print("Login successful: \(user.email)")
        } catch {
            errorMessage = error.localizedDescription
        }
        
        isLoading = false
    }
    
    // MARK: - Validation
    private func validate() -> Bool {
        guard !email.isEmpty else {
            errorMessage = "Email is required"
            return false
        }
        
        guard !password.isEmpty else {
            errorMessage = "Password is required"
            return false
        }
        
        return true
    }
}
