//
//  RegisterViewModel.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation
import Combine

final class RegisterViewModel: ObservableObject {
    // MARK: - Published Properties
    @Published var email: String = ""
    @Published var password: String = ""
    @Published var name: String = ""
    @Published var isLoading: Bool = false
    @Published var errorMessage: String?
    @Published var isRegistered: Bool = false
    
    // MARK: - Dependencies
    private let registerUseCase: RegisterUseCaseProtocol
    private var onRegisterSuccess: (() -> Void)?
    private var cancellables = Set<AnyCancellable>()
    
    // MARK: - Initialization
    init(registerUseCase: RegisterUseCaseProtocol, onRegisterSuccess: (() -> Void)? = nil) {
        self.registerUseCase = registerUseCase
        self.onRegisterSuccess = onRegisterSuccess
    }
    
    // MARK: - Actions
    @MainActor
    func register() async {
        guard validate() else { return }
        
        isLoading = true
        errorMessage = nil
        
        do {
            let user = try await registerUseCase.execute(email: email, password: password, name: name)
            isRegistered = true
            onRegisterSuccess?()
            print("Registration successful: \(user.email)")
        } catch {
            errorMessage = error.localizedDescription
        }
        
        isLoading = false
    }
    
    // MARK: - Validation
    private func validate() -> Bool {
        guard !name.isEmpty else {
            errorMessage = "Name is required"
            return false
        }
        
        guard !email.isEmpty else {
            errorMessage = "Email is required"
            return false
        }
        
        guard !password.isEmpty else {
            errorMessage = "Password is required"
            return false
        }
        
        guard password.count >= 6 else {
            errorMessage = "Password must be at least 6 characters"
            return false
        }
        
        return true
    }
}
