//
//  AuthAssembly.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation
import Swinject

final class AuthAssembly: Assembly {
    func assemble(container: Container) {
        // Data Sources
        container.register(AuthRemoteDataSource.self) { r in
            let networkManager = r.resolve(NetworkManagerProtocol.self)!
            return AuthRemoteDataSource(networkManager: networkManager)
        }.inObjectScope(.container)
        
        container.register(AuthLocalDataSource.self) { _ in
            return AuthLocalDataSource()
        }.inObjectScope(.container)
        
        // Repository
        container.register(AuthRepositoryProtocol.self) { r in
            let remoteDataSource = r.resolve(AuthRemoteDataSource.self)!
            let localDataSource = r.resolve(AuthLocalDataSource.self)!
            return AuthRepository(
                remoteDataSource: remoteDataSource,
                localDataSource: localDataSource
            )
        }.inObjectScope(.container)
        
        // Use Cases
        container.register(LoginUseCaseProtocol.self) { r in
            let repository = r.resolve(AuthRepositoryProtocol.self)!
            return LoginUseCase(repository: repository)
        }
        
        // ViewModels
        container.register(LoginViewModel.self) { r in
            let loginUseCase = r.resolve(LoginUseCaseProtocol.self)!
            return LoginViewModel(loginUseCase: loginUseCase)
        }
    }
}
