//
//  AuthRemoteDataSource.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

final class AuthRemoteDataSource {
    private let networkManager: NetworkManagerProtocol
    
    init(networkManager: NetworkManagerProtocol) {
        self.networkManager = networkManager
    }
    
    func login(email: String, password: String) async throws -> AuthResponse {
        let endpoint = APIEndpoint.login(email: email, password: password)
        return try await networkManager.request(endpoint)
    }
    
    func register(email: String, password: String, name: String) async throws -> AuthResponse {
        let endpoint = APIEndpoint.register(email: email, password: password, name: name)
        return try await networkManager.request(endpoint)
    }
}

// MARK: - Response Models
struct AuthResponse: Codable {
    let token: String
    let user: UserResponse
    
    func toEntity() -> UserEntity {
        return UserEntity(
            id: user.id,
            email: user.email,
            name: user.name
        )
    }
}

struct UserResponse: Codable {
    let id: String
    let email: String
    let name: String
}
