//
//  AuthLocalDataSource.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

final class AuthLocalDataSource {
    private let userDefaults: UserDefaults
    private let tokenKey = "auth_token"
    
    init(userDefaults: UserDefaults = .standard) {
        self.userDefaults = userDefaults
    }
    
    func saveToken(_ token: String) async throws {
        userDefaults.set(token, forKey: tokenKey)
    }
    
    func getToken() -> String? {
        return userDefaults.string(forKey: tokenKey)
    }
    
    func clearToken() async throws {
        userDefaults.removeObject(forKey: tokenKey)
    }
}
