//
//  AuthRepository.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

final class AuthRepository: AuthRepositoryProtocol {
    private let remoteDataSource: AuthRemoteDataSource
    private let localDataSource: AuthLocalDataSource
    
    init(remoteDataSource: AuthRemoteDataSource, localDataSource: AuthLocalDataSource) {
        self.remoteDataSource = remoteDataSource
        self.localDataSource = localDataSource
    }
    
    func login(email: String, password: String) async throws -> UserEntity {
        let response = try await remoteDataSource.login(email: email, password: password)
        try await localDataSource.saveToken(response.token)
        return response.toEntity()
    }
    
    func register(email: String, password: String, name: String) async throws -> UserEntity {
        let response = try await remoteDataSource.register(email: email, password: password, name: name)
        try await localDataSource.saveToken(response.token)
        return response.toEntity()
    }
    
    func logout() async throws {
        try await localDataSource.clearToken()
    }
}

// MARK: - Entities
struct UserEntity {
    let id: String
    let email: String
    let name: String
}
