//
//  LoginViewModelTests.swift
//  {{PROJECT_NAME}}Tests
//
//  Generated by AppFoundation
//

import XCTest
@testable import {{PROJECT_NAME}}

@MainActor
final class LoginViewModelTests: XCTestCase {
    var sut: LoginViewModel!
    var mockUseCase: MockLoginUseCase!
    
    override func setUp() {
        super.setUp()
        mockUseCase = MockLoginUseCase()
        sut = LoginViewModel(loginUseCase: mockUseCase)
    }
    
    override func tearDown() {
        sut = nil
        mockUseCase = nil
        super.tearDown()
    }
    
    func testLoginSuccess() async {
        // Given
        sut.email = "test@example.com"
        sut.password = "password123"
        mockUseCase.shouldSucceed = true
        
        // When
        await sut.login()
        
        // Then
        XCTAssertTrue(sut.isAuthenticated)
        XCTAssertNil(sut.errorMessage)
        XCTAssertFalse(sut.isLoading)
    }
    
    func testLoginFailure() async {
        // Given
        sut.email = "test@example.com"
        sut.password = "wrong"
        mockUseCase.shouldSucceed = false
        
        // When
        await sut.login()
        
        // Then
        XCTAssertFalse(sut.isAuthenticated)
        XCTAssertNotNil(sut.errorMessage)
        XCTAssertFalse(sut.isLoading)
    }
    
    func testValidationEmptyEmail() async {
        // Given
        sut.email = ""
        sut.password = "password123"
        
        // When
        await sut.login()
        
        // Then
        XCTAssertEqual(sut.errorMessage, "Email is required")
    }
}

// MARK: - Mock
class MockLoginUseCase: LoginUseCaseProtocol {
    var shouldSucceed = true
    
    func execute(email: String, password: String) async throws -> UserEntity {
        if shouldSucceed {
            return UserEntity(id: "1", email: email, name: "Test User")
        } else {
            throw NSError(domain: "Auth", code: 401, userInfo: [NSLocalizedDescriptionKey: "Invalid credentials"])
        }
    }
}
