//
//  AuthRepositoryProtocol.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

protocol AuthRepositoryProtocol {
    func login(email: String, password: String) async throws -> UserEntity
    func register(email: String, password: String, name: String) async throws -> UserEntity
    func logout() async throws
}
