//
//  LoginUseCase.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

protocol LoginUseCaseProtocol {
    func execute(email: String, password: String) async throws -> UserEntity
}

final class LoginUseCase: LoginUseCaseProtocol {
    private let repository: AuthRepositoryProtocol
    
    init(repository: AuthRepositoryProtocol) {
        self.repository = repository
    }
    
    func execute(email: String, password: String) async throws -> UserEntity {
        return try await repository.login(email: email, password: password)
    }
}
