//
//  RegisterUseCase.swift
//  {{PROJECT_NAME}}
//
//  Generated by AppFoundation
//

import Foundation

protocol RegisterUseCaseProtocol {
    func execute(email: String, password: String, name: String) async throws -> UserEntity
}

final class RegisterUseCase: RegisterUseCaseProtocol {
    private let repository: AuthRepositoryProtocol
    
    init(repository: AuthRepositoryProtocol) {
        self.repository = repository
    }
    
    func execute(email: String, password: String, name: String) async throws -> UserEntity {
        return try await repository.register(email: email, password: password, name: name)
    }
}
